spring:

  datasource:
    url: jdbc:mariadb://localhost:3306/tailerbox
    username: cwlee02
    password: secret

#  data:
#    web:
#      pageable:
#        one-indexed-parameters: on
#        default-page-size: 20
