spring:
  application:
    name: tailerbox
  profiles:
    active: local

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/**/*-mapper.xml

pagehelper:
  auto-dialect: true
  helper-dialect: mariadb
  page-size-zero: false
  reasonable: true
  offset-as-page-num: false
  row-bounds-with-count: false
  auto-runtime-dialect: false
  close-conn: true
  default-count: true
