spring:

  datasource:
    url: jdbc:mariadb://localhost:3306/tailerbox
    username: cwlee02
    password: secret

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/**/*Mapper.xml
